import { Task } from '../types'

const now = new Date()
const fmt = (d: Date) => d.toISOString()
const daysFromNow = (n: number) => {
  const d = new Date(now)
  d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

export const SAMPLE_TASKS: Task[] = [
  // 工作
  {
    id: 'task-001',
    title: '完成 Q2 产品线视觉规范手册',
    area: 'work',
    status: 'in_progress',
    importance: 5,
    urgency: 4,
    longTermValue: 5,
    difficulty: 3,
    energy: 'high',
    deadline: daysFromNow(5),
    estimatedMinutes: 240,
    tags: ['视觉规范', '手册', '季度'],
    notes: '需要包含：配色体系、字体规范、排版规则、产品摄影风格指南',
    nextAction: '整理现有素材，搭建文档框架',
    createdAt: fmt(new Date(now.getTime() - 7 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-002',
    title: '安排下周新品拍摄',
    area: 'work',
    status: 'todo',
    importance: 5,
    urgency: 5,
    longTermValue: 3,
    difficulty: 2,
    energy: 'medium',
    deadline: daysFromNow(2),
    estimatedMinutes: 60,
    tags: ['拍摄', '新品', '协调'],
    notes: '需确认：场地、设备、模特、道具',
    nextAction: '联系摄影助理确认档期',
    createdAt: fmt(new Date(now.getTime() - 3 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-003',
    title: '审查电商主图设计稿',
    area: 'work',
    status: 'waiting',
    importance: 4,
    urgency: 3,
    longTermValue: 3,
    difficulty: 2,
    energy: 'medium',
    deadline: daysFromNow(3),
    estimatedMinutes: 90,
    blocker: '等待设计师提交初稿',
    tags: ['电商', '主图', '审图'],
    nextAction: '等待设计师提交，到期前跟进',
    createdAt: fmt(new Date(now.getTime() - 2 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-004',
    title: '部门月度绩效反馈面谈',
    area: 'work',
    status: 'todo',
    importance: 4,
    urgency: 3,
    longTermValue: 4,
    difficulty: 3,
    energy: 'high',
    deadline: daysFromNow(8),
    estimatedMinutes: 120,
    tags: ['管理', '绩效', '面谈'],
    nextAction: '提前准备每位成员的反馈要点',
    createdAt: fmt(new Date(now.getTime() - 5 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-005',
    title: '整理品牌摄影素材库',
    area: 'work',
    status: 'paused',
    importance: 3,
    urgency: 2,
    longTermValue: 4,
    difficulty: 2,
    energy: 'low',
    estimatedMinutes: 180,
    tags: ['素材库', '整理', '归档'],
    notes: '分类：产品 / 场景 / 生活方式 / 品牌故事',
    createdAt: fmt(new Date(now.getTime() - 14 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-006',
    title: '提交 6 月预算申请',
    area: 'work',
    status: 'todo',
    importance: 5,
    urgency: 5,
    longTermValue: 2,
    difficulty: 1,
    energy: 'low',
    deadline: daysFromNow(-1),
    estimatedMinutes: 30,
    tags: ['预算', '行政', '紧急'],
    nextAction: '填写预算表并发给财务',
    createdAt: fmt(new Date(now.getTime() - 1 * 86400000)),
    updatedAt: fmt(now),
  },

  // 学习成长
  {
    id: 'task-007',
    title: '完成 ComfyUI 高级节点学习',
    area: 'learning',
    status: 'in_progress',
    importance: 5,
    urgency: 3,
    longTermValue: 5,
    difficulty: 4,
    energy: 'high',
    estimatedMinutes: 300,
    tags: ['AIGC', 'ComfyUI', '深度学习'],
    notes: '重点：ControlNet + IPAdapter 工作流搭建',
    nextAction: '完成第 3 章实战练习',
    createdAt: fmt(new Date(now.getTime() - 10 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-008',
    title: '研究 Claude Code 自动化工作流',
    area: 'learning',
    status: 'in_progress',
    importance: 5,
    urgency: 3,
    longTermValue: 5,
    difficulty: 3,
    energy: 'high',
    estimatedMinutes: 240,
    tags: ['Claude Code', 'AI', '自动化'],
    notes: '探索：批量图片处理、报告生成、数据分析自动化',
    nextAction: '搭建第一个图片批处理 Pipeline',
    createdAt: fmt(new Date(now.getTime() - 4 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-009',
    title: '阅读《深度工作》并做笔记',
    area: 'learning',
    status: 'todo',
    importance: 3,
    urgency: 1,
    longTermValue: 4,
    difficulty: 2,
    energy: 'medium',
    deadline: daysFromNow(30),
    estimatedMinutes: 360,
    tags: ['读书', '效率', '专注'],
    createdAt: fmt(new Date(now.getTime() - 6 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-010',
    title: '学习尼康 Z 系统新固件功能',
    area: 'learning',
    status: 'inbox',
    importance: 3,
    urgency: 2,
    longTermValue: 3,
    difficulty: 1,
    energy: 'low',
    estimatedMinutes: 60,
    tags: ['摄影', '器材', '尼康'],
    createdAt: fmt(now),
    updatedAt: fmt(now),
  },

  // 财务
  {
    id: 'task-011',
    title: '整理 5 月报销单据',
    area: 'finance',
    status: 'todo',
    importance: 4,
    urgency: 4,
    longTermValue: 2,
    difficulty: 1,
    energy: 'low',
    deadline: daysFromNow(4),
    estimatedMinutes: 45,
    tags: ['报销', '财务', '月度'],
    nextAction: '收集发票，填写报销表',
    createdAt: fmt(new Date(now.getTime() - 2 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-012',
    title: '审视个人资产配置',
    area: 'finance',
    status: 'todo',
    importance: 4,
    urgency: 2,
    longTermValue: 5,
    difficulty: 3,
    energy: 'medium',
    deadline: daysFromNow(14),
    estimatedMinutes: 120,
    tags: ['投资', '资产', '规划'],
    notes: '检查：基金定投收益、险种保额是否充足',
    createdAt: fmt(new Date(now.getTime() - 7 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-013',
    title: '更新个人年度财务目标追踪表',
    area: 'finance',
    status: 'todo',
    importance: 3,
    urgency: 2,
    longTermValue: 4,
    difficulty: 2,
    energy: 'low',
    estimatedMinutes: 60,
    tags: ['财务规划', '目标', '复盘'],
    createdAt: fmt(new Date(now.getTime() - 20 * 86400000)),
    updatedAt: fmt(now),
  },

  // 生活
  {
    id: 'task-014',
    title: '预约年度体检',
    area: 'life',
    status: 'todo',
    importance: 5,
    urgency: 3,
    longTermValue: 5,
    difficulty: 1,
    energy: 'low',
    deadline: daysFromNow(10),
    estimatedMinutes: 20,
    tags: ['健康', '体检', '年度'],
    nextAction: '打电话预约医院体检套餐',
    createdAt: fmt(new Date(now.getTime() - 5 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-015',
    title: '建立每日运动习惯（30min/天）',
    area: 'life',
    status: 'in_progress',
    importance: 5,
    urgency: 3,
    longTermValue: 5,
    difficulty: 3,
    energy: 'medium',
    estimatedMinutes: 30,
    tags: ['健康', '运动', '习惯'],
    notes: '当前完成率约 60%，目标 90%+',
    nextAction: '今日完成 30 分钟慢跑',
    createdAt: fmt(new Date(now.getTime() - 30 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-016',
    title: '整理家中储物间',
    area: 'life',
    status: 'inbox',
    importance: 2,
    urgency: 1,
    longTermValue: 2,
    difficulty: 2,
    energy: 'medium',
    estimatedMinutes: 180,
    tags: ['整理', '生活', '周末'],
    createdAt: fmt(new Date(now.getTime() - 3 * 86400000)),
    updatedAt: fmt(now),
  },
  {
    id: 'task-017',
    title: '给父母安排一次短途旅行',
    area: 'life',
    status: 'todo',
    importance: 5,
    urgency: 2,
    longTermValue: 5,
    difficulty: 2,
    energy: 'medium',
    deadline: daysFromNow(60),
    estimatedMinutes: 120,
    tags: ['家人', '旅行', '情感'],
    nextAction: '确定时间，查询目的地攻略',
    createdAt: fmt(new Date(now.getTime() - 8 * 86400000)),
    updatedAt: fmt(now),
  },

  // 已完成示例
  {
    id: 'task-020',
    title: '完成品牌视频脚本审核',
    area: 'work',
    status: 'done',
    importance: 4,
    urgency: 4,
    longTermValue: 3,
    difficulty: 2,
    energy: 'medium',
    estimatedMinutes: 60,
    tags: ['视频', '脚本', '审核'],
    createdAt: fmt(new Date(now.getTime() - 10 * 86400000)),
    updatedAt: fmt(new Date(now.getTime() - 1 * 86400000)),
  },
]

